name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release-Tag (z. B. v1.2.3)'
        required: true
        type: string

jobs:
  call-reusable:
    uses: mjbohn/GithubWorkflows/.github/workflows/dotnet-build-and-release-win.yml@main
    with:
      tag: ${{ inputs.tag }}
      project_path: 'src/RMQ-Client'
      zip_name: 'RMQ-Client.zip'
      configuration: 'Release'
